# Example showing how to run FovVideoVDP on a numpy array with a video
# The video is autogenerated in this example. See ex_aliasing.py for an example in which video is loaded from .mp4 files

import os, sys
import numpy as np
import ex_utils as utils

sys.path.append('..')
from pyfvvdp import fvvdp
import time


# The frame to use for the video
I_ref = utils.imread(os.path.join('..', 'example_media', 'tree.jpg'))

N = 60*4 # The number of frames
fps = 30 # Frames per second
sigma_max = 2

V_ref = np.repeat(I_ref[...,np.newaxis], N, axis=3) # Reference video (in colour). 
SIGMAs = np.concatenate((np.linspace(0.01, sigma_max, N//2), np.linspace(sigma_max, 0.01, N//2)))
V_blur = utils.imgaussblur(V_ref, SIGMAs)

fv = fvvdp(display_name='standard_4k', heatmap=None)

start = time.time()
Q_JOD, stats = fv.predict( V_blur.astype('uint8'), V_ref, dim_order="HWCF", frames_per_second=fps )
end = time.time()

print(f'Quality for blur-over-time: {Q_JOD:.3f} JOD (took {end-start:.4f} secs to compute)')
